/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "D1_aliases.h"
#include "D1.h"
#include "D2_aliases.h"
#include "D2.h"
#include "isr_1.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "UART_1.h"
#include "isr_UART_1_Tx.h"
#include "isr_UART_1_Rx.h"
#include "ADC_1.h"
#include "VDD1_aliases.h"
#include "VDD1.h"
#include "SW1_aliases.h"
#include "SW1.h"
#include "ADC_2.h"
#include "VDD2_aliases.h"
#include "VDD2.h"
#include "LED4_aliases.h"
#include "LED4.h"
#include "LED3_aliases.h"
#include "LED3.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "Em_EEPROM.h"
#include "Clock_Tick.h"
#include "isr_Tick.h"
#include "LED1_aliases.h"
#include "LED1.h"
#include "LED2_aliases.h"
#include "LED2.h"
#include "P2_aliases.h"
#include "P2.h"
#include "SleepTimer.h"
#include "isr_SleepTimer.h"
#include "UART_2.h"
#include "isr_UART_2_Tx.h"
#include "isr_UART_2_Rx.h"
#include "Clock_1.h"
#include "UART_1_IntClock.h"
#include "ADC_1_IRQ.h"
#include "ADC_1_theACLK.h"
#include "ADC_2_IRQ.h"
#include "ADC_2_theACLK.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "UART_2_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

